steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "northamerica-northeast1-docker.pkg.dev/microservices-dev-434418/image-registry/products-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "northamerica-northeast1-docker.pkg.dev/microservices-dev-434418/image-registry/products-ms",
      ]
      
options:
  logging: CLOUD_LOGGING_ONLY

